version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: vista-graph-neo4j-emcellent
    restart: unless-stopped
    ports:
      - "7475:7474" # HTTP/Browser
      - "7688:7687" # Bolt protocol
    volumes:
      - vista_emcellent_neo4j_data:/data
      - vista_emcellent_neo4j_logs:/logs
      - vista_emcellent_neo4j_import:/var/lib/neo4j/import
      - vista_emcellent_neo4j_plugins:/plugins
    environment:
      # Initial password for neo4j user
      NEO4J_AUTH: neo4j/password
      # Accept license agreement (required for Neo4j 5+)
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      # Memory configuration
      NEO4J_server_memory_heap_initial__size: 512m
      NEO4J_server_memory_heap_max__size: 2G
      NEO4J_server_memory_pagecache_size: 512m
      # Enable APOC procedures (if needed later)
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      # Database configuration
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
      NEO4J_dbms_security_procedures_allowlist: "apoc.*"
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:7474 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  vista_emcellent_neo4j_data:
    driver: local
  vista_emcellent_neo4j_logs:
    driver: local
  vista_emcellent_neo4j_import:
    driver: local
  vista_emcellent_neo4j_plugins:
    driver: local
